name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yarn install and build
        run: yarn install && yarn compile

  deploy:
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install vsce and deps
        run: |
          yarn global add vsce
          yarn install
      - name: Publish
        run: |
          echo $RELEASE_VERSION
          vsce publish -p $VSCODE_TOKEN --no-git-tag-version ${RELEASE_VERSION:1}
        env:
          VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
