name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: CI 
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Package
        run: |
          npm install -g vsce
          mkdir -p bin/
          npm i
          vsce package --allow-star-activation -o bin/langoustine-vscode.vsix

      - uses: actions/upload-artifact@v3
        with:
          path: bin/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "bin/**/*.vsix"
